# Generated by Django 2.0.7 on 2018-08-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senseur',
            name='mouvement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
