# Generated by Django 2.0.7 on 2018-08-12 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cowapp', '0004_delete_monthlyweatherbycity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senseur',
            name='date_stocker',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
