# Generated by Django 2.0.7 on 2018-08-12 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cowapp', '0005_auto_20180812_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senseur',
            name='date_stocker',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
