# Generated by Django 2.0.7 on 2018-08-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowapp', '0006_auto_20180812_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestation',
            name='gestation',
            field=models.BooleanField(default=False),
        ),
    ]
