# Generated by Django 2.0.7 on 2018-08-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowapp', '0007_auto_20180813_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestation',
            name='vache',
        ),
        migrations.AddField(
            model_name='vache',
            name='gestation',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Gestation',
        ),
    ]
